// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.1; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ----------------- //
// ssd1306_spi_slave //
// ----------------- //

#define ssd1306_spi_slave_wrap_target 0
#define ssd1306_spi_slave_wrap 14
#define ssd1306_spi_slave_pio_version 0

static __pio_const uint16_t ssd1306_spi_slave_program_instructions[] = {
            //     .wrap_target
    0x2000, //  0: wait   0 gpio, 0
    0xe026, //  1: set    x, 6
    0x2081, //  2: wait   1 gpio, 1
    0x4001, //  3: in     pins, 1
    0x2001, //  4: wait   0 gpio, 1
    0x00ce, //  5: jmp    pin, 14
    0x0042, //  6: jmp    x--, 2
    0x2081, //  7: wait   1 gpio, 1
    0x4002, //  8: in     pins, 2
    0x2001, //  9: wait   0 gpio, 1
    0x8020, // 10: push   block
    0xc000, // 11: irq    nowait 0
    0x00ce, // 12: jmp    pin, 14
    0x0001, // 13: jmp    1
    0xa0c3, // 14: mov    isr, null
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program ssd1306_spi_slave_program = {
    .instructions = ssd1306_spi_slave_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = ssd1306_spi_slave_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config ssd1306_spi_slave_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ssd1306_spi_slave_wrap_target, offset + ssd1306_spi_slave_wrap);
    return c;
}
#endif

