// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.1; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// -------- //
// vfd_scan //
// -------- //

#define vfd_scan_wrap_target 0
#define vfd_scan_wrap 24
#define vfd_scan_pio_version 0

static __pio_const uint16_t vfd_scan_program_instructions[] = {
            //     .wrap_target
    0x2027, //  0: wait   0 pin, 7
    0x20a7, //  1: wait   1 pin, 7
    0xe300, //  2: set    pins, 0                [3]
    0xe302, //  3: set    pins, 2                [3]
    0xe303, //  4: set    pins, 3                [3]
    0xe302, //  5: set    pins, 2                [3]
    0xe042, //  6: set    y, 2
    0xe02f, //  7: set    x, 15
    0x7001, //  8: out    pins, 1         side 0
    0xb842, //  9: nop                    side 1
    0x7001, // 10: out    pins, 1         side 0
    0xb842, // 11: nop                    side 1
    0x7001, // 12: out    pins, 1         side 0
    0xb842, // 13: nop                    side 1
    0x7001, // 14: out    pins, 1         side 0
    0xb842, // 15: nop                    side 1
    0x7001, // 16: out    pins, 1         side 0
    0xb842, // 17: nop                    side 1
    0x7001, // 18: out    pins, 1         side 0
    0xb842, // 19: nop                    side 1
    0x7001, // 20: out    pins, 1         side 0
    0xb842, // 21: nop                    side 1
    0x7001, // 22: out    pins, 1         side 0
    0x1848, // 23: jmp    x--, 8          side 1
    0x0387, // 24: jmp    y--, 7                 [3]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program vfd_scan_program = {
    .instructions = vfd_scan_program_instructions,
    .length = 25,
    .origin = -1,
    .pio_version = vfd_scan_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config vfd_scan_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vfd_scan_wrap_target, offset + vfd_scan_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

